input {
  kafka {
    bootstrap_servers => "s3-kafka:9092"
    topics => ["math.results"]
    codec => "json"
  }
}

filter {
  date {
    match => ["timestamp", "UNIX"]
    target => "@timestamp"
  }
  mutate {
    remove_field => ["@version"]
  }
}

output {
  elasticsearch {
    hosts => ["http://s3-elasticsearch:9200"]
    index => "math-results"
  }
}
